export const BEGIN_AJAX_CALL= "BEGIN_AJAX_CALL";
export const AJAX_CALL_ERROR= "AJAX_CALL_ERROR";

export const LOAD_CATEGORIES_SUCCESS= "LOAD_CATEGORIES_SUCCESS";

export const LOAD_USERS_SUCCESS= "LOAD_USERS_SUCCESS";
export const CREATE_USER_SUCCESS= "CREATE_USER_SUCCESS";